trigger:
- master
pool:
  #vmImage: 'ubuntu-latest'
  name: azure-keda



variables:
  tag: '$(Build.BuildId)'


steps:


#steps:
#- task: Docker@2
#  inputs:
#    containerRegistry: 'harbortaas'
#    repository: 'tzl-shrd-harbor.taas.vodafone.local/furkan-nginx/nginx'
#    command: 'buildAndPush'
#    Dockerfile: '**/Dockerfile'
#    tags: $(tag)

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'furkanakgun/basitnginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)
