trigger:
- master
pool:
  #vmImage: 'ubuntu-latest'
  name: azure-keda



variables:
  tag: '$(Build.BuildId)'


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'tzl-shrd-harbor.taas.vodafone.local/furkanakgun/basitnginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)
