trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
  name: tzl-poc
  demands:
  - agent.name -equals 'tzl-poc-ado-5f9b9bd77-j9shs'

variables:
  tag: '$(Build.BuildId)'


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'harbortaas'
    repository: 'tzl-shrd-harbor.taas.vodafone.local/furkan-nginx/nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)
