trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
  name: tzl-shrd

variables:
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'harbortaas'
    repository: 'furkan-nginx/nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)
