trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
  name: tzl-poc

variables:
  tag: '$(Build.BuildId)'


- task: Docker@2
  inputs:
    containerRegistry: 'harbortaas'
    repository: 'tzl-shrd-harbor.taas.vodafone.local/furkan-nginx/nginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)
