# azure-pipeline.yml
trigger:
- master

resources:
- repo: self

variables:
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

stages:
- stage: BuildAndPush
  displayName: Build and Push stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
      name: tzl-shrd
    steps:
    - task: Docker@2
      displayName: Build and Push Docker image
      inputs:
        containerRegistry: 'HarborRegistryServiceConnection'
        repository: 'furkan-nginx/furkan-nginx'
        command: 'buildAndPush'
        Dockerfile: $(dockerfilePath)
        tags: $(tag)
