trigger:
- master
pool:
  #vmImage: 'ubuntu-latest'
  name: azure-keda



variables:
  tag: '$(Build.BuildId)'


steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub-furkan'
    repository: 'furkanakgun/basitnginx'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: $(tag)
